name: On push, deploying to Test
on: [push]
jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-build-deploy.yml@add-common-wf
    with:
      process_env: Test
    secrets: inherit
