name: On push, deploying to Test
on: 
  push:
    tags-ignore: 
      - *
jobs:
  run-build-and-deploy:
    uses: octopusden/octopus-base/.github/workflows/common-py-build-deploy.yml@main
    with:
      process_env: Test
      python_versions: '3'
    secrets: inherit
